---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdemoapp
  labels:
    app: springdemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springdemoapp
  template:
    metadata:
      labels:
        app: springdemoapp
    spec:
      containers:
        - name: springdemoapp
          image: rajshivaram7/springboot-demo-app:latest
          resources:
            limits:
              memory: 1024M
              cpu: "1"
          envFrom:
            - secretRef:
                name: springdemo-postgres-connection
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
